server:
  port: 8081
  
spring:
  application:
    name: natural-client
  data:
    mongodb:
      uri: mongodb://localhost:27017/natural-client
     
    kafka:
      bootstrap-servers: localhost:9092
      
    redis:
       database: 0
       host: localhost
       port: 6379
       timeout: 60000
       password: 1234
   
gateway:
   baseUrl: http://localhost:8080
   
#eureka:
  #client:
    #serviceUrl:
      #defaultZone: http://${eureka.instance.hostname}:8099/eureka/
    #register-with-eureka: true
    #fetch-registry: true
  #instance:
    #prefer-ip-address: true #false si va ip
    #hostname: localhost #azure reemplazo de local  192.168.1.11
    

    
